# Generated by Django 5.1.7 on 2025-04-14 14:24

from django.db import migrations
from accounts.models import CustomUser

def create_admin_user(apps, schema_editor):
    # Check if the admin user already exists
    if not CustomUser.objects.filter(username="admin").exists():
        admin_user = CustomUser.objects.create_superuser('admin', 'admin@example.com', '12345')
        admin_user.role = 'admin'  # Assigning the role
        admin_user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_must_change_password_and_more'),
    ]

    operations = [
        migrations.RunPython(create_admin_user)
    ]
