# Generated by Django 5.1.7 on 2025-04-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_printjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Printing', 'Printing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=50),
        ),
    ]
